In [4]:
import argparse
import gym
from vans_gym.envs import VansEnvsSeq
from vans_gym.solvers import CirqSolverR, Checker
from vans_gym.models import DuelDQN
import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm
import tensorflow as tf

In [5]:
solver = CirqSolverR(n_qubits = 2, observable_name="Ising_",qlr=0.05,qepochs=100)
checker = Checker(solver)
env = VansEnvsSeq(solver,checker=checker, depth_circuit=3)

model = DuelDQN(env, name="WorkingOut",priority_scale=0.1, learning_rate=0.01, tau=0.5)
model.replay_buffer.load("DuelDQN/run_9/data_collected/")

In [ ]:
for k in tqdm(range(100)):
    model.learn_step(batch_size=64)

In [7]:
(states, actions, rewards, nstates, dones), importance, indices = model.replay_buffer.get_minibatch(batch_size=1, priority_scale=model.priority_scale)

In [8]:
model.prim_qnet.predict(tf.stack(np.array([[-1,-1,-1]]).astype(np.float32)))

array([[-0.02945315, -0.00605267, -0.03324292,  0.09253455,  0.08927465,
        -0.14925666]], dtype=float32)

In [9]:
model.prim_qnet.predict(tf.stack(np.array([[3.,-1,-1]]).astype(np.float32)))

array([[-0.0974717 ,  0.37892026,  0.03494024,  0.2073739 , -0.08444621,
        -0.42722702]], dtype=float32)

In [10]:
model.prim_qnet.predict(tf.stack(np.array([[3.,5.,3.]]).astype(np.float32)))

array([[ 0.05134374,  0.41767755,  0.11996649, -0.08629922, -0.628417  ,
        -0.32184175]], dtype=float32)